version: '2.4'
services:
  postgres:
    ulimits:
      memlock:
        soft: -1
        hard: -1
    container_name: postgresql_quarkus_search
    environment:
      - POSTGRES_USER=quarkus_test
      - POSTGRES_PASSWORD=quarkus_test
      - POSTGRES_DB=searchdb
    ports:
      - '5432:5432'
    image: 'postgres:11.3'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    command: postgres -c max_connections=10000
    mem_limit: 2000m
  elasticsearch:
    container_name: elasticsearch_quarkus_search
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
    image: 'docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.0'
